---
- block:

    - include_tasks: "repo-{{ ansible_os_family }}.yml"

    - name: install chrome
      package:
        name: "google-chrome-{{ google_chrome_stability }}"
        state: present

  become: true
  become_user: root
  tags:
    - google-chrome
